export const CHANGE_FLOWER = "CHANGE_FLOWER";
export const ADD_FLOWER = "ADD_FLOWER";
export const ADD_BEE = "ADD_BEE";

export const PICKUP_POLLEN = "PICKUP_POLLEN";
export const DROP_POLLEN = "DROP_POLLEN";

export const BEE_CAN_FLY = "BEE_CAN_FLY";

export const ADD_RECESSIVE_COLOR = "ADD_RECESSIVE_COLOR";
export const REMOVE_RECESSIVE_COLOR = "REMOVE_RECESSIVE_COLOR";
