export const CHANGE_PUNNETT_FLOWER = "CHANGE_PUNNETT_FLOWER";
export const ADD_FLOWER_TO_STORE = "ADD_FLOWER_TO_STORE";
export const SET_FIRST_FLOWER_POSITION = "SET_FIRST_FLOWER_POSITION";
export const ADD_BATCH_OF_FLOWERS_TO_STORE = "ADD_BATCH_OF_FLOWERS_TO_STORE";

export const PICKUP_POLLEN = "PICKUP_POLLEN";
export const DROP_POLLEN = "DROP_POLLEN";

export const BEE_CAN_FLY = "BEE_CAN_FLY";
export const ADD_BEE = "ADD_BEE";

export const ADD_RECESSIVE_ALLELE = "ADD_RECESSIVE_ALLELE";
export const REMOVE_RECESSIVE_ALLELE = "REMOVE_RECESSIVE_ALLELE";

export const CHANGE_FLOWER_NAME = "CHANGE_FLOWER_NAME";

export const SHOW_TOOLTIP = "SHOW_TOOLTIP";
export const HIDE_TOOLTIP = "HIDE_TOOLTIP";

export const ADD_TILES_TO_STORE = "ADD_TILES_TO_STORE";
// export const TILE_FILLED = "TILE_FILLED";
export const SET_AVAILABLE_TILES = "SET_AVAILABLE_TILES";
