export const CHANGE_FLOWER = "CHANGE_FLOWER";
export const ADD_FLOWER_TO_STORE = "ADD_FLOWER_TO_STORE";
export const ADD_BEE = "ADD_BEE";

export const PICKUP_POLLEN = "PICKUP_POLLEN";
export const DROP_POLLEN = "DROP_POLLEN";

export const BEE_CAN_FLY = "BEE_CAN_FLY";

export const ADD_RECESSIVE_ALLELE = "ADD_RECESSIVE_ALLELE";
export const REMOVE_RECESSIVE_ALLELE = "REMOVE_RECESSIVE_ALLELE";

export const CHANGE_FLOWER_NAME = "CHANGE_FLOWER_NAME";
